# DataSource configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/treasure
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=treasure
spring.datasource.password=treasure

spring.main.allow-bean-definition-overriding=true

# JOOQ properties
spring.jooq.sql-dialect=postgres

# Liquibase
spring.liquibase.change-log=classpath:liquibase/db.changelog-master.xml

# Logging properties
logging.file.name=service.log
logging.level.com.github.onotoliy.opposite.treasure=TRACE

# Context path properties
server.port=8081
server.servlet.context-path=/api/treasure/v1

treasure.keycloak.base-url=http://localhost:8081/auth
treasure.keycloak.realm=realm
treasure.keycloak.client-id=client
treasure.keycloak.username=username
treasure.keycloak.password=password
