# DataSource configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/treasure
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=treasure
spring.datasource.password=treasure

spring.main.allow-bean-definition-overriding=true

# JOOQ properties
spring.jooq.sql-dialect=postgres

# Liquibase
spring.liquibase.change-log=classpath:liquibase/db.changelog-master.xml

# Logging properties
logging.file.name=service.log
logging.level.com.github.onotoliy.opposite.treasure=TRACE

# Context path properties
server.port=8081
server.servlet.context-path=/api/treasure/v1

# ��������� ����������� URL
treasure.roles.default=member
treasure.roles.modification=member
treasure.roles.reading=member

# Keycloak ������ �������������
treasure.keycloak.url=http://185.12.95.242/auth
treasure.keycloak.realm=treasure
treasure.keycloak.client=admin-cli
treasure.keycloak.username=rest-admin
treasure.keycloak.password=password

# Настройки безопасности
spring.security.oauth2.client.provider.opposite.issuer-uri=https://185.12.95.242:44/realms/opposite
spring.security.oauth2.client.registration.opposite.provider=opposite
spring.security.oauth2.client.registration.opposite.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.opposite.client-id=backend
spring.security.oauth2.client.registration.opposite.client-authentication-method=Bearer
spring.security.oauth2.client.registration.opposite.client-secret=BaVj0782i5LyQgsl9ZB50ZwwIRCixNkl
spring.security.oauth2.client.registration.opposite.scope=openid,offline_access,profile

logging.level.org.springframework.security=DEBUG