/*
 * This file is generated by jOOQ.
 */
package com.github.onotoliy.opposite.treasure.jooq.tables.records;


import com.github.onotoliy.opposite.treasure.jooq.tables.TreasureLog;

import java.sql.Timestamp;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Логи
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TreasureLogRecord extends UpdatableRecordImpl<TreasureLogRecord> implements Record7<UUID, UUID, String, Timestamp, String, String, String> {

    private static final long serialVersionUID = 149273711;

    /**
     * Setter for <code>public.treasure_log.guid</code>. Уникальный идентификатор
     */
    public void setGuid(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.treasure_log.guid</code>. Уникальный идентификатор
     */
    public UUID getGuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.treasure_log.author</code>. Автор
     */
    public void setAuthor(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.treasure_log.author</code>. Автор
     */
    public UUID getAuthor() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.treasure_log.level</code>. Уровень логирования
     */
    public void setLevel(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.treasure_log.level</code>. Уровень логирования
     */
    public String getLevel() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.treasure_log.creation_date</code>. Дата создания записи
     */
    public void setCreationDate(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.treasure_log.creation_date</code>. Дата создания записи
     */
    public Timestamp getCreationDate() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>public.treasure_log.message</code>. Сообщение
     */
    public void setMessage(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.treasure_log.message</code>. Сообщение
     */
    public String getMessage() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.treasure_log.bean_name</code>. Название класса
     */
    public void setBeanName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.treasure_log.bean_name</code>. Название класса
     */
    public String getBeanName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.treasure_log.stack_trace</code>. Stack Trace
     */
    public void setStackTrace(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.treasure_log.stack_trace</code>. Stack Trace
     */
    public String getStackTrace() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<UUID, UUID, String, Timestamp, String, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<UUID, UUID, String, Timestamp, String, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field1() {
        return TreasureLog.TREASURE_LOG.GUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field2() {
        return TreasureLog.TREASURE_LOG.AUTHOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TreasureLog.TREASURE_LOG.LEVEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return TreasureLog.TREASURE_LOG.CREATION_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TreasureLog.TREASURE_LOG.MESSAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return TreasureLog.TREASURE_LOG.BEAN_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return TreasureLog.TREASURE_LOG.STACK_TRACE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID component1() {
        return getGuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID component2() {
        return getAuthor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getLevel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getCreationDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getMessage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getBeanName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getStackTrace();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value1() {
        return getGuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value2() {
        return getAuthor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getLevel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getCreationDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getMessage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getBeanName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getStackTrace();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TreasureLogRecord value1(UUID value) {
        setGuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TreasureLogRecord value2(UUID value) {
        setAuthor(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TreasureLogRecord value3(String value) {
        setLevel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TreasureLogRecord value4(Timestamp value) {
        setCreationDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TreasureLogRecord value5(String value) {
        setMessage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TreasureLogRecord value6(String value) {
        setBeanName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TreasureLogRecord value7(String value) {
        setStackTrace(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TreasureLogRecord values(UUID value1, UUID value2, String value3, Timestamp value4, String value5, String value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TreasureLogRecord
     */
    public TreasureLogRecord() {
        super(TreasureLog.TREASURE_LOG);
    }

    /**
     * Create a detached, initialised TreasureLogRecord
     */
    public TreasureLogRecord(UUID guid, UUID author, String level, Timestamp creationDate, String message, String beanName, String stackTrace) {
        super(TreasureLog.TREASURE_LOG);

        set(0, guid);
        set(1, author);
        set(2, level);
        set(3, creationDate);
        set(4, message);
        set(5, beanName);
        set(6, stackTrace);
    }
}
