/*
 * This file is generated by jOOQ.
 */
package com.github.onotoliy.opposite.treasure.jooq.tables.records;


import com.github.onotoliy.opposite.treasure.jooq.tables.TreasureEvent;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * События
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TreasureEventRecord extends UpdatableRecordImpl<TreasureEventRecord> implements Record8<UUID, String, BigDecimal, BigDecimal, Timestamp, UUID, Timestamp, Timestamp> {

    private static final long serialVersionUID = -1719391960;

    /**
     * Setter for <code>public.treasure_event.guid</code>. Уникальный идентификатор
     */
    public void setGuid(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.treasure_event.guid</code>. Уникальный идентификатор
     */
    public UUID getGuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.treasure_event.name</code>. Название
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.treasure_event.name</code>. Название
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.treasure_event.contribution</code>. Взнос с одного человека
     */
    public void setContribution(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.treasure_event.contribution</code>. Взнос с одного человека
     */
    public BigDecimal getContribution() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>public.treasure_event.total</code>. Общая сумма
     */
    public void setTotal(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.treasure_event.total</code>. Общая сумма
     */
    public BigDecimal getTotal() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>public.treasure_event.deadline</code>. Конечный срок сдачи
     */
    public void setDeadline(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.treasure_event.deadline</code>. Конечный срок сдачи
     */
    public Timestamp getDeadline() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>public.treasure_event.author</code>. Автор
     */
    public void setAuthor(UUID value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.treasure_event.author</code>. Автор
     */
    public UUID getAuthor() {
        return (UUID) get(5);
    }

    /**
     * Setter for <code>public.treasure_event.creation_date</code>. Дата создания записи
     */
    public void setCreationDate(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.treasure_event.creation_date</code>. Дата создания записи
     */
    public Timestamp getCreationDate() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>public.treasure_event.deletion_date</code>. Дата удаления записи
     */
    public void setDeletionDate(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.treasure_event.deletion_date</code>. Дата удаления записи
     */
    public Timestamp getDeletionDate() {
        return (Timestamp) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<UUID, String, BigDecimal, BigDecimal, Timestamp, UUID, Timestamp, Timestamp> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<UUID, String, BigDecimal, BigDecimal, Timestamp, UUID, Timestamp, Timestamp> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field1() {
        return TreasureEvent.TREASURE_EVENT.GUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TreasureEvent.TREASURE_EVENT.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field3() {
        return TreasureEvent.TREASURE_EVENT.CONTRIBUTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field4() {
        return TreasureEvent.TREASURE_EVENT.TOTAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return TreasureEvent.TREASURE_EVENT.DEADLINE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field6() {
        return TreasureEvent.TREASURE_EVENT.AUTHOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return TreasureEvent.TREASURE_EVENT.CREATION_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return TreasureEvent.TREASURE_EVENT.DELETION_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID component1() {
        return getGuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component3() {
        return getContribution();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component4() {
        return getTotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getDeadline();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID component6() {
        return getAuthor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getCreationDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getDeletionDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value1() {
        return getGuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value3() {
        return getContribution();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value4() {
        return getTotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getDeadline();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value6() {
        return getAuthor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getCreationDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getDeletionDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TreasureEventRecord value1(UUID value) {
        setGuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TreasureEventRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TreasureEventRecord value3(BigDecimal value) {
        setContribution(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TreasureEventRecord value4(BigDecimal value) {
        setTotal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TreasureEventRecord value5(Timestamp value) {
        setDeadline(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TreasureEventRecord value6(UUID value) {
        setAuthor(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TreasureEventRecord value7(Timestamp value) {
        setCreationDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TreasureEventRecord value8(Timestamp value) {
        setDeletionDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TreasureEventRecord values(UUID value1, String value2, BigDecimal value3, BigDecimal value4, Timestamp value5, UUID value6, Timestamp value7, Timestamp value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TreasureEventRecord
     */
    public TreasureEventRecord() {
        super(TreasureEvent.TREASURE_EVENT);
    }

    /**
     * Create a detached, initialised TreasureEventRecord
     */
    public TreasureEventRecord(UUID guid, String name, BigDecimal contribution, BigDecimal total, Timestamp deadline, UUID author, Timestamp creationDate, Timestamp deletionDate) {
        super(TreasureEvent.TREASURE_EVENT);

        set(0, guid);
        set(1, name);
        set(2, contribution);
        set(3, total);
        set(4, deadline);
        set(5, author);
        set(6, creationDate);
        set(7, deletionDate);
    }
}
