/*
 * This file is generated by jOOQ.
 */
package com.github.onotoliy.opposite.treasure.jooq.tables.records;


import com.github.onotoliy.opposite.treasure.jooq.tables.TreasureNotification;

import java.sql.Timestamp;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Транзакции
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TreasureNotificationRecord extends UpdatableRecordImpl<TreasureNotificationRecord> implements Record10<UUID, String, String, String, String, UUID, Timestamp, UUID, Timestamp, Timestamp> {

    private static final long serialVersionUID = -1328629810;

    /**
     * Setter for <code>public.treasure_notification.guid</code>. Уникальный идентификатор
     */
    public void setGuid(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.treasure_notification.guid</code>. Уникальный идентификатор
     */
    public UUID getGuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.treasure_notification.name</code>. Заголовок
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.treasure_notification.name</code>. Заголовок
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.treasure_notification.message</code>. Сообщение
     */
    public void setMessage(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.treasure_notification.message</code>. Сообщение
     */
    public String getMessage() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.treasure_notification.notification_type</code>. Тип уведомления
     */
    public void setNotificationType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.treasure_notification.notification_type</code>. Тип уведомления
     */
    public String getNotificationType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.treasure_notification.delivery_type</code>. Тип доставки
     */
    public void setDeliveryType(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.treasure_notification.delivery_type</code>. Тип доставки
     */
    public String getDeliveryType() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.treasure_notification.object_uuid</code>. Уникальный идентификатор объекта
     */
    public void setObjectUuid(UUID value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.treasure_notification.object_uuid</code>. Уникальный идентификатор объекта
     */
    public UUID getObjectUuid() {
        return (UUID) get(5);
    }

    /**
     * Setter for <code>public.treasure_notification.delivery_date</code>. Дата доставки
     */
    public void setDeliveryDate(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.treasure_notification.delivery_date</code>. Дата доставки
     */
    public Timestamp getDeliveryDate() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>public.treasure_notification.author</code>. Автор
     */
    public void setAuthor(UUID value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.treasure_notification.author</code>. Автор
     */
    public UUID getAuthor() {
        return (UUID) get(7);
    }

    /**
     * Setter for <code>public.treasure_notification.creation_date</code>. Дата создания записи
     */
    public void setCreationDate(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.treasure_notification.creation_date</code>. Дата создания записи
     */
    public Timestamp getCreationDate() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>public.treasure_notification.deletion_date</code>. Дата удаления записи
     */
    public void setDeletionDate(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.treasure_notification.deletion_date</code>. Дата удаления записи
     */
    public Timestamp getDeletionDate() {
        return (Timestamp) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<UUID, String, String, String, String, UUID, Timestamp, UUID, Timestamp, Timestamp> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<UUID, String, String, String, String, UUID, Timestamp, UUID, Timestamp, Timestamp> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field1() {
        return TreasureNotification.TREASURE_NOTIFICATION.GUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TreasureNotification.TREASURE_NOTIFICATION.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TreasureNotification.TREASURE_NOTIFICATION.MESSAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TreasureNotification.TREASURE_NOTIFICATION.NOTIFICATION_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TreasureNotification.TREASURE_NOTIFICATION.DELIVERY_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field6() {
        return TreasureNotification.TREASURE_NOTIFICATION.OBJECT_UUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return TreasureNotification.TREASURE_NOTIFICATION.DELIVERY_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field8() {
        return TreasureNotification.TREASURE_NOTIFICATION.AUTHOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return TreasureNotification.TREASURE_NOTIFICATION.CREATION_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return TreasureNotification.TREASURE_NOTIFICATION.DELETION_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID component1() {
        return getGuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getMessage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getNotificationType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getDeliveryType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID component6() {
        return getObjectUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getDeliveryDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID component8() {
        return getAuthor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getCreationDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component10() {
        return getDeletionDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value1() {
        return getGuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getMessage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getNotificationType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getDeliveryType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value6() {
        return getObjectUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getDeliveryDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value8() {
        return getAuthor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getCreationDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getDeletionDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TreasureNotificationRecord value1(UUID value) {
        setGuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TreasureNotificationRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TreasureNotificationRecord value3(String value) {
        setMessage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TreasureNotificationRecord value4(String value) {
        setNotificationType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TreasureNotificationRecord value5(String value) {
        setDeliveryType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TreasureNotificationRecord value6(UUID value) {
        setObjectUuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TreasureNotificationRecord value7(Timestamp value) {
        setDeliveryDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TreasureNotificationRecord value8(UUID value) {
        setAuthor(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TreasureNotificationRecord value9(Timestamp value) {
        setCreationDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TreasureNotificationRecord value10(Timestamp value) {
        setDeletionDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TreasureNotificationRecord values(UUID value1, String value2, String value3, String value4, String value5, UUID value6, Timestamp value7, UUID value8, Timestamp value9, Timestamp value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TreasureNotificationRecord
     */
    public TreasureNotificationRecord() {
        super(TreasureNotification.TREASURE_NOTIFICATION);
    }

    /**
     * Create a detached, initialised TreasureNotificationRecord
     */
    public TreasureNotificationRecord(UUID guid, String name, String message, String notificationType, String deliveryType, UUID objectUuid, Timestamp deliveryDate, UUID author, Timestamp creationDate, Timestamp deletionDate) {
        super(TreasureNotification.TREASURE_NOTIFICATION);

        set(0, guid);
        set(1, name);
        set(2, message);
        set(3, notificationType);
        set(4, deliveryType);
        set(5, objectUuid);
        set(6, deliveryDate);
        set(7, author);
        set(8, creationDate);
        set(9, deletionDate);
    }
}
