/*
 * This file is generated by jOOQ.
 */
package com.github.onotoliy.opposite.treasure.jooq.tables.records;


import com.github.onotoliy.opposite.treasure.jooq.tables.TreasureDeposit;

import java.math.BigDecimal;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Депозиты
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TreasureDepositRecord extends UpdatableRecordImpl<TreasureDepositRecord> implements Record2<UUID, BigDecimal> {

    private static final long serialVersionUID = -891218391;

    /**
     * Setter for <code>public.treasure_deposit.user_uuid</code>. Пользователь
     */
    public void setUserUuid(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.treasure_deposit.user_uuid</code>. Пользователь
     */
    public UUID getUserUuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.treasure_deposit.deposit</code>. Депозит
     */
    public void setDeposit(BigDecimal value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.treasure_deposit.deposit</code>. Депозит
     */
    public BigDecimal getDeposit() {
        return (BigDecimal) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<UUID, BigDecimal> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<UUID, BigDecimal> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field1() {
        return TreasureDeposit.TREASURE_DEPOSIT.USER_UUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field2() {
        return TreasureDeposit.TREASURE_DEPOSIT.DEPOSIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID component1() {
        return getUserUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component2() {
        return getDeposit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value1() {
        return getUserUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value2() {
        return getDeposit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TreasureDepositRecord value1(UUID value) {
        setUserUuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TreasureDepositRecord value2(BigDecimal value) {
        setDeposit(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TreasureDepositRecord values(UUID value1, BigDecimal value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TreasureDepositRecord
     */
    public TreasureDepositRecord() {
        super(TreasureDeposit.TREASURE_DEPOSIT);
    }

    /**
     * Create a detached, initialised TreasureDepositRecord
     */
    public TreasureDepositRecord(UUID userUuid, BigDecimal deposit) {
        super(TreasureDeposit.TREASURE_DEPOSIT);

        set(0, userUuid);
        set(1, deposit);
    }
}
