/*
 * This file is generated by jOOQ.
 */
package com.github.onotoliy.opposite.treasure.jooq.tables.records;


import com.github.onotoliy.opposite.treasure.jooq.tables.TreasureTransaction;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Транзакции
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TreasureTransactionRecord extends UpdatableRecordImpl<TreasureTransactionRecord> implements Record10<UUID, String, BigDecimal, UUID, UUID, String, UUID, Timestamp, Timestamp, Timestamp> {

    private static final long serialVersionUID = 669097188;

    /**
     * Setter for <code>public.treasure_transaction.guid</code>.
     */
    public void setGuid(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.treasure_transaction.guid</code>.
     */
    public UUID getGuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.treasure_transaction.name</code>. Название
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.treasure_transaction.name</code>. Название
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.treasure_transaction.cash</code>. Денежные средсва
     */
    public void setCash(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.treasure_transaction.cash</code>. Денежные средсва
     */
    public BigDecimal getCash() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>public.treasure_transaction.user_guid</code>. Пользователь
     */
    public void setUserGuid(UUID value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.treasure_transaction.user_guid</code>. Пользователь
     */
    public UUID getUserGuid() {
        return (UUID) get(3);
    }

    /**
     * Setter for <code>public.treasure_transaction.event_guid</code>. Событие
     */
    public void setEventGuid(UUID value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.treasure_transaction.event_guid</code>. Событие
     */
    public UUID getEventGuid() {
        return (UUID) get(4);
    }

    /**
     * Setter for <code>public.treasure_transaction.type</code>. Тип
     */
    public void setType(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.treasure_transaction.type</code>. Тип
     */
    public String getType() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.treasure_transaction.author</code>. Автор
     */
    public void setAuthor(UUID value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.treasure_transaction.author</code>. Автор
     */
    public UUID getAuthor() {
        return (UUID) get(6);
    }

    /**
     * Setter for <code>public.treasure_transaction.creation_date</code>. Дата создания записи
     */
    public void setCreationDate(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.treasure_transaction.creation_date</code>. Дата создания записи
     */
    public Timestamp getCreationDate() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>public.treasure_transaction.deletion_date</code>. Дата удаления записи
     */
    public void setDeletionDate(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.treasure_transaction.deletion_date</code>. Дата удаления записи
     */
    public Timestamp getDeletionDate() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>public.treasure_transaction.transaction_date</code>. Дата совершения транзации
     */
    public void setTransactionDate(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.treasure_transaction.transaction_date</code>. Дата совершения транзации
     */
    public Timestamp getTransactionDate() {
        return (Timestamp) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<UUID, String, BigDecimal, UUID, UUID, String, UUID, Timestamp, Timestamp, Timestamp> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<UUID, String, BigDecimal, UUID, UUID, String, UUID, Timestamp, Timestamp, Timestamp> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field1() {
        return TreasureTransaction.TREASURE_TRANSACTION.GUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TreasureTransaction.TREASURE_TRANSACTION.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field3() {
        return TreasureTransaction.TREASURE_TRANSACTION.CASH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field4() {
        return TreasureTransaction.TREASURE_TRANSACTION.USER_GUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field5() {
        return TreasureTransaction.TREASURE_TRANSACTION.EVENT_GUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return TreasureTransaction.TREASURE_TRANSACTION.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field7() {
        return TreasureTransaction.TREASURE_TRANSACTION.AUTHOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return TreasureTransaction.TREASURE_TRANSACTION.CREATION_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return TreasureTransaction.TREASURE_TRANSACTION.DELETION_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return TreasureTransaction.TREASURE_TRANSACTION.TRANSACTION_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID component1() {
        return getGuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component3() {
        return getCash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID component4() {
        return getUserGuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID component5() {
        return getEventGuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID component7() {
        return getAuthor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getCreationDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getDeletionDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component10() {
        return getTransactionDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value1() {
        return getGuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value3() {
        return getCash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value4() {
        return getUserGuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value5() {
        return getEventGuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value7() {
        return getAuthor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getCreationDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getDeletionDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getTransactionDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TreasureTransactionRecord value1(UUID value) {
        setGuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TreasureTransactionRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TreasureTransactionRecord value3(BigDecimal value) {
        setCash(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TreasureTransactionRecord value4(UUID value) {
        setUserGuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TreasureTransactionRecord value5(UUID value) {
        setEventGuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TreasureTransactionRecord value6(String value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TreasureTransactionRecord value7(UUID value) {
        setAuthor(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TreasureTransactionRecord value8(Timestamp value) {
        setCreationDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TreasureTransactionRecord value9(Timestamp value) {
        setDeletionDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TreasureTransactionRecord value10(Timestamp value) {
        setTransactionDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TreasureTransactionRecord values(UUID value1, String value2, BigDecimal value3, UUID value4, UUID value5, String value6, UUID value7, Timestamp value8, Timestamp value9, Timestamp value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TreasureTransactionRecord
     */
    public TreasureTransactionRecord() {
        super(TreasureTransaction.TREASURE_TRANSACTION);
    }

    /**
     * Create a detached, initialised TreasureTransactionRecord
     */
    public TreasureTransactionRecord(UUID guid, String name, BigDecimal cash, UUID userGuid, UUID eventGuid, String type, UUID author, Timestamp creationDate, Timestamp deletionDate, Timestamp transactionDate) {
        super(TreasureTransaction.TREASURE_TRANSACTION);

        set(0, guid);
        set(1, name);
        set(2, cash);
        set(3, userGuid);
        set(4, eventGuid);
        set(5, type);
        set(6, author);
        set(7, creationDate);
        set(8, deletionDate);
        set(9, transactionDate);
    }
}
