/*
 * This file is generated by jOOQ.
 */
package com.github.onotoliy.opposite.treasure.jooq.tables.records;


import com.github.onotoliy.opposite.treasure.jooq.tables.TreasureVersion;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Версия таблицы
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TreasureVersionRecord extends UpdatableRecordImpl<TreasureVersionRecord> implements Record2<String, BigDecimal> {

    private static final long serialVersionUID = 1224722807;

    /**
     * Setter for <code>public.treasure_version.name</code>. Название таблицы
     */
    public void setName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.treasure_version.name</code>. Название таблицы
     */
    public String getName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.treasure_version.version</code>. Версия
     */
    public void setVersion(BigDecimal value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.treasure_version.version</code>. Версия
     */
    public BigDecimal getVersion() {
        return (BigDecimal) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, BigDecimal> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, BigDecimal> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return TreasureVersion.TREASURE_VERSION.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field2() {
        return TreasureVersion.TREASURE_VERSION.VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component2() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value2() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TreasureVersionRecord value1(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TreasureVersionRecord value2(BigDecimal value) {
        setVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TreasureVersionRecord values(String value1, BigDecimal value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TreasureVersionRecord
     */
    public TreasureVersionRecord() {
        super(TreasureVersion.TREASURE_VERSION);
    }

    /**
     * Create a detached, initialised TreasureVersionRecord
     */
    public TreasureVersionRecord(String name, BigDecimal version) {
        super(TreasureVersion.TREASURE_VERSION);

        set(0, name);
        set(1, version);
    }
}
