/*
 * This file is generated by jOOQ.
 */
package com.github.onotoliy.opposite.treasure.jooq.tables.records;


import com.github.onotoliy.opposite.treasure.jooq.tables.TreasureCashbox;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * Касса
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TreasureCashboxRecord extends TableRecordImpl<TreasureCashboxRecord> implements Record2<Timestamp, BigDecimal> {

    private static final long serialVersionUID = 286798653;

    /**
     * Setter for <code>public.treasure_cashbox.last_update_date</code>. Дата последненго изменения
     */
    public void setLastUpdateDate(Timestamp value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.treasure_cashbox.last_update_date</code>. Дата последненго изменения
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp) get(0);
    }

    /**
     * Setter for <code>public.treasure_cashbox.deposit</code>. Сумма в кассе
     */
    public void setDeposit(BigDecimal value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.treasure_cashbox.deposit</code>. Сумма в кассе
     */
    public BigDecimal getDeposit() {
        return (BigDecimal) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Timestamp, BigDecimal> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Timestamp, BigDecimal> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field1() {
        return TreasureCashbox.TREASURE_CASHBOX.LAST_UPDATE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field2() {
        return TreasureCashbox.TREASURE_CASHBOX.DEPOSIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component1() {
        return getLastUpdateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component2() {
        return getDeposit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value1() {
        return getLastUpdateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value2() {
        return getDeposit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TreasureCashboxRecord value1(Timestamp value) {
        setLastUpdateDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TreasureCashboxRecord value2(BigDecimal value) {
        setDeposit(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TreasureCashboxRecord values(Timestamp value1, BigDecimal value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TreasureCashboxRecord
     */
    public TreasureCashboxRecord() {
        super(TreasureCashbox.TREASURE_CASHBOX);
    }

    /**
     * Create a detached, initialised TreasureCashboxRecord
     */
    public TreasureCashboxRecord(Timestamp lastUpdateDate, BigDecimal deposit) {
        super(TreasureCashbox.TREASURE_CASHBOX);

        set(0, lastUpdateDate);
        set(1, deposit);
    }
}
