/*
 * This file is generated by jOOQ.
 */
package com.github.onotoliy.opposite.treasure.jooq.tables;


import com.github.onotoliy.opposite.treasure.jooq.Indexes;
import com.github.onotoliy.opposite.treasure.jooq.Keys;
import com.github.onotoliy.opposite.treasure.jooq.Public;
import com.github.onotoliy.opposite.treasure.jooq.tables.records.TreasureLogRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * Логи
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TreasureLog extends TableImpl<TreasureLogRecord> {

    private static final long serialVersionUID = 319579040;

    /**
     * The reference instance of <code>public.treasure_log</code>
     */
    public static final TreasureLog TREASURE_LOG = new TreasureLog();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TreasureLogRecord> getRecordType() {
        return TreasureLogRecord.class;
    }

    /**
     * The column <code>public.treasure_log.guid</code>. Уникальный идентификатор
     */
    public final TableField<TreasureLogRecord, UUID> GUID = createField("guid", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "Уникальный идентификатор");

    /**
     * The column <code>public.treasure_log.author</code>. Автор
     */
    public final TableField<TreasureLogRecord, UUID> AUTHOR = createField("author", org.jooq.impl.SQLDataType.UUID, this, "Автор");

    /**
     * The column <code>public.treasure_log.level</code>. Уровень логирования
     */
    public final TableField<TreasureLogRecord, String> LEVEL = createField("level", org.jooq.impl.SQLDataType.VARCHAR(255), this, "Уровень логирования");

    /**
     * The column <code>public.treasure_log.creation_date</code>. Дата создания записи
     */
    public final TableField<TreasureLogRecord, Timestamp> CREATION_DATE = createField("creation_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "Дата создания записи");

    /**
     * The column <code>public.treasure_log.message</code>. Сообщение
     */
    public final TableField<TreasureLogRecord, String> MESSAGE = createField("message", org.jooq.impl.SQLDataType.VARCHAR(255), this, "Сообщение");

    /**
     * The column <code>public.treasure_log.bean_name</code>. Название класса
     */
    public final TableField<TreasureLogRecord, String> BEAN_NAME = createField("bean_name", org.jooq.impl.SQLDataType.VARCHAR(255), this, "Название класса");

    /**
     * The column <code>public.treasure_log.stack_trace</code>. Stack Trace
     */
    public final TableField<TreasureLogRecord, String> STACK_TRACE = createField("stack_trace", org.jooq.impl.SQLDataType.VARCHAR(255), this, "Stack Trace");

    /**
     * Create a <code>public.treasure_log</code> table reference
     */
    public TreasureLog() {
        this(DSL.name("treasure_log"), null);
    }

    /**
     * Create an aliased <code>public.treasure_log</code> table reference
     */
    public TreasureLog(String alias) {
        this(DSL.name(alias), TREASURE_LOG);
    }

    /**
     * Create an aliased <code>public.treasure_log</code> table reference
     */
    public TreasureLog(Name alias) {
        this(alias, TREASURE_LOG);
    }

    private TreasureLog(Name alias, Table<TreasureLogRecord> aliased) {
        this(alias, aliased, null);
    }

    private TreasureLog(Name alias, Table<TreasureLogRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("Логи"));
    }

    public <O extends Record> TreasureLog(Table<O> child, ForeignKey<O, TreasureLogRecord> key) {
        super(child, key, TREASURE_LOG);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.TREASURE_LOG_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TreasureLogRecord> getPrimaryKey() {
        return Keys.TREASURE_LOG_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TreasureLogRecord>> getKeys() {
        return Arrays.<UniqueKey<TreasureLogRecord>>asList(Keys.TREASURE_LOG_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TreasureLog as(String alias) {
        return new TreasureLog(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TreasureLog as(Name alias) {
        return new TreasureLog(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TreasureLog rename(String name) {
        return new TreasureLog(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TreasureLog rename(Name name) {
        return new TreasureLog(name, null);
    }
}
