/*
 * This file is generated by jOOQ.
 */
package com.github.onotoliy.opposite.treasure.jooq;


import com.github.onotoliy.opposite.treasure.jooq.tables.TreasureDebt;
import com.github.onotoliy.opposite.treasure.jooq.tables.TreasureDeposit;
import com.github.onotoliy.opposite.treasure.jooq.tables.TreasureEvent;
import com.github.onotoliy.opposite.treasure.jooq.tables.TreasureException;
import com.github.onotoliy.opposite.treasure.jooq.tables.TreasureLog;
import com.github.onotoliy.opposite.treasure.jooq.tables.TreasureNotification;
import com.github.onotoliy.opposite.treasure.jooq.tables.TreasureTransaction;
import com.github.onotoliy.opposite.treasure.jooq.tables.TreasureVersion;
import com.github.onotoliy.opposite.treasure.jooq.tables.records.TreasureDebtRecord;
import com.github.onotoliy.opposite.treasure.jooq.tables.records.TreasureDepositRecord;
import com.github.onotoliy.opposite.treasure.jooq.tables.records.TreasureEventRecord;
import com.github.onotoliy.opposite.treasure.jooq.tables.records.TreasureExceptionRecord;
import com.github.onotoliy.opposite.treasure.jooq.tables.records.TreasureLogRecord;
import com.github.onotoliy.opposite.treasure.jooq.tables.records.TreasureNotificationRecord;
import com.github.onotoliy.opposite.treasure.jooq.tables.records.TreasureTransactionRecord;
import com.github.onotoliy.opposite.treasure.jooq.tables.records.TreasureVersionRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<TreasureDebtRecord> TREASURE_DEBT_USER_UUID_EVENT_GUID_KEY = UniqueKeys0.TREASURE_DEBT_USER_UUID_EVENT_GUID_KEY;
    public static final UniqueKey<TreasureDepositRecord> TREASURE_DEPOSIT_PKEY = UniqueKeys0.TREASURE_DEPOSIT_PKEY;
    public static final UniqueKey<TreasureEventRecord> TREASURE_EVENT_PKEY = UniqueKeys0.TREASURE_EVENT_PKEY;
    public static final UniqueKey<TreasureExceptionRecord> TREASURE_EXCEPTION_PKEY = UniqueKeys0.TREASURE_EXCEPTION_PKEY;
    public static final UniqueKey<TreasureLogRecord> TREASURE_LOG_PKEY = UniqueKeys0.TREASURE_LOG_PKEY;
    public static final UniqueKey<TreasureNotificationRecord> TREASURE_NOTIFICATION_PKEY = UniqueKeys0.TREASURE_NOTIFICATION_PKEY;
    public static final UniqueKey<TreasureTransactionRecord> TREASURE_TRANSACTION_PKEY = UniqueKeys0.TREASURE_TRANSACTION_PKEY;
    public static final UniqueKey<TreasureVersionRecord> TREASURE_VERSION_PKEY = UniqueKeys0.TREASURE_VERSION_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<TreasureDebtRecord, TreasureEventRecord> TREASURE_DEBT__FK_TT_EVENT = ForeignKeys0.TREASURE_DEBT__FK_TT_EVENT;
    public static final ForeignKey<TreasureTransactionRecord, TreasureEventRecord> TREASURE_TRANSACTION__FK_TT_EVENT = ForeignKeys0.TREASURE_TRANSACTION__FK_TT_EVENT;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<TreasureDebtRecord> TREASURE_DEBT_USER_UUID_EVENT_GUID_KEY = Internal.createUniqueKey(TreasureDebt.TREASURE_DEBT, "treasure_debt_user_uuid_event_guid_key", TreasureDebt.TREASURE_DEBT.USER_UUID, TreasureDebt.TREASURE_DEBT.EVENT_GUID);
        public static final UniqueKey<TreasureDepositRecord> TREASURE_DEPOSIT_PKEY = Internal.createUniqueKey(TreasureDeposit.TREASURE_DEPOSIT, "treasure_deposit_pkey", TreasureDeposit.TREASURE_DEPOSIT.USER_UUID);
        public static final UniqueKey<TreasureEventRecord> TREASURE_EVENT_PKEY = Internal.createUniqueKey(TreasureEvent.TREASURE_EVENT, "treasure_event_pkey", TreasureEvent.TREASURE_EVENT.GUID);
        public static final UniqueKey<TreasureExceptionRecord> TREASURE_EXCEPTION_PKEY = Internal.createUniqueKey(TreasureException.TREASURE_EXCEPTION, "treasure_exception_pkey", TreasureException.TREASURE_EXCEPTION.GUID);
        public static final UniqueKey<TreasureLogRecord> TREASURE_LOG_PKEY = Internal.createUniqueKey(TreasureLog.TREASURE_LOG, "treasure_log_pkey", TreasureLog.TREASURE_LOG.GUID);
        public static final UniqueKey<TreasureNotificationRecord> TREASURE_NOTIFICATION_PKEY = Internal.createUniqueKey(TreasureNotification.TREASURE_NOTIFICATION, "treasure_notification_pkey", TreasureNotification.TREASURE_NOTIFICATION.GUID);
        public static final UniqueKey<TreasureTransactionRecord> TREASURE_TRANSACTION_PKEY = Internal.createUniqueKey(TreasureTransaction.TREASURE_TRANSACTION, "treasure_transaction_pkey", TreasureTransaction.TREASURE_TRANSACTION.GUID);
        public static final UniqueKey<TreasureVersionRecord> TREASURE_VERSION_PKEY = Internal.createUniqueKey(TreasureVersion.TREASURE_VERSION, "treasure_version_pkey", TreasureVersion.TREASURE_VERSION.NAME);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<TreasureDebtRecord, TreasureEventRecord> TREASURE_DEBT__FK_TT_EVENT = Internal.createForeignKey(com.github.onotoliy.opposite.treasure.jooq.Keys.TREASURE_EVENT_PKEY, TreasureDebt.TREASURE_DEBT, "treasure_debt__fk_tt_event", TreasureDebt.TREASURE_DEBT.EVENT_GUID);
        public static final ForeignKey<TreasureTransactionRecord, TreasureEventRecord> TREASURE_TRANSACTION__FK_TT_EVENT = Internal.createForeignKey(com.github.onotoliy.opposite.treasure.jooq.Keys.TREASURE_EVENT_PKEY, TreasureTransaction.TREASURE_TRANSACTION, "treasure_transaction__fk_tt_event", TreasureTransaction.TREASURE_TRANSACTION.EVENT_GUID);
    }
}
