/*
 * This file is generated by jOOQ.
 */
package com.github.onotoliy.opposite.treasure.jooq;


import com.github.onotoliy.opposite.treasure.jooq.tables.TreasureCashbox;
import com.github.onotoliy.opposite.treasure.jooq.tables.TreasureDebt;
import com.github.onotoliy.opposite.treasure.jooq.tables.TreasureDeposit;
import com.github.onotoliy.opposite.treasure.jooq.tables.TreasureEvent;
import com.github.onotoliy.opposite.treasure.jooq.tables.TreasureException;
import com.github.onotoliy.opposite.treasure.jooq.tables.TreasureLog;
import com.github.onotoliy.opposite.treasure.jooq.tables.TreasureNotification;
import com.github.onotoliy.opposite.treasure.jooq.tables.TreasureTransaction;
import com.github.onotoliy.opposite.treasure.jooq.tables.TreasureVersion;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -798000976;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * Касса
     */
    public final TreasureCashbox TREASURE_CASHBOX = com.github.onotoliy.opposite.treasure.jooq.tables.TreasureCashbox.TREASURE_CASHBOX;

    /**
     * Долги
     */
    public final TreasureDebt TREASURE_DEBT = com.github.onotoliy.opposite.treasure.jooq.tables.TreasureDebt.TREASURE_DEBT;

    /**
     * Депозиты
     */
    public final TreasureDeposit TREASURE_DEPOSIT = com.github.onotoliy.opposite.treasure.jooq.tables.TreasureDeposit.TREASURE_DEPOSIT;

    /**
     * События
     */
    public final TreasureEvent TREASURE_EVENT = com.github.onotoliy.opposite.treasure.jooq.tables.TreasureEvent.TREASURE_EVENT;

    /**
     * Описание ошибки устройства
     */
    public final TreasureException TREASURE_EXCEPTION = com.github.onotoliy.opposite.treasure.jooq.tables.TreasureException.TREASURE_EXCEPTION;

    /**
     * Логи
     */
    public final TreasureLog TREASURE_LOG = com.github.onotoliy.opposite.treasure.jooq.tables.TreasureLog.TREASURE_LOG;

    /**
     * Транзакции
     */
    public final TreasureNotification TREASURE_NOTIFICATION = com.github.onotoliy.opposite.treasure.jooq.tables.TreasureNotification.TREASURE_NOTIFICATION;

    /**
     * Транзакции
     */
    public final TreasureTransaction TREASURE_TRANSACTION = com.github.onotoliy.opposite.treasure.jooq.tables.TreasureTransaction.TREASURE_TRANSACTION;

    /**
     * Версия таблицы
     */
    public final TreasureVersion TREASURE_VERSION = com.github.onotoliy.opposite.treasure.jooq.tables.TreasureVersion.TREASURE_VERSION;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            TreasureCashbox.TREASURE_CASHBOX,
            TreasureDebt.TREASURE_DEBT,
            TreasureDeposit.TREASURE_DEPOSIT,
            TreasureEvent.TREASURE_EVENT,
            TreasureException.TREASURE_EXCEPTION,
            TreasureLog.TREASURE_LOG,
            TreasureNotification.TREASURE_NOTIFICATION,
            TreasureTransaction.TREASURE_TRANSACTION,
            TreasureVersion.TREASURE_VERSION);
    }
}
